### PR TITLE
issue fixed for non ssl certificate.

### PR DESCRIPTION
**Pull request by jangidgirish**

### CODE REVIEW

**Comment by jsor** [comment]
No, we won't do that. See eg. https://paragonie.com/blog/2017/10/certainty-automated-cacert-pem-management-for-php-software

**Comment by jangidgirish** [comment]
Hello Jan, how i can fix following problem in my app, the code is returning warning..

**Comment by jsor** [comment]
A good starting point is the link i posted above. Also, make sure you have the openssl extension installed so there's a wrapper for https: http://php.net/manual/de/wrappers.http.php

**Comment by jangidgirish** [comment]
the issue has been fixed by OpenSSL extension, thank you.

**Pull request closed without merging**
